# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.6'
    hooks:
      - id: prettier
        files: ^app/.*\.(ts|tsx|css)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.56.0'
    hooks:
      - id: eslint
