version: '3.8'

services:
  frontend:
    container_name: staging
    build:
      context: .
      dockerfile: app/staging.Dockerfile
    ports:
      - 3002:80
    volumes:
      - /app/node_modules
      - ./app:/app
    env_file:
      - ./.env.staging
    environment:
      - BACKEND_URL=https://backend-staging-2fa7.up.railway.app
      - CHOKIDAR_USEPOLLING=true
