version: '3.8'

services:
  frontend-dev:
    container_name: dev
    build:
      context: .
      dockerfile: app/dev.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./app:/app
      - /app/node_modules
    env_file:
      - app/.env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - backend-network

networks:
  backend-network:
    external: false
