version: '3.8'

services:
  frontend:
    container_name: staging
    build:
      context: .
      dockerfile: app/staging.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./app:/app
    env_file:
      - app/.env.staging
    environment:
      - CHOKIDAR_USEPOLLING=true
